# azure-pipelines.yml

trigger:
  branches:
    include:
      - main

pool: default

steps:
- script: |
    echo "Downloading Java JDK..."
    wget -q https://builds.openlogic.com/downloadJDK/openlogic-openjdk/8u372-b07/openlogic-openjdk-8u372-b07-linux-x64.tar.gz
    tar -xzf jdk-8u302-linux-x64.tar.gz -C /usr/lib/jvm
    export JAVA_HOME=/usr/lib/jvm
    export PATH=$JAVA_HOME/bin:$PATH
  displayName: 'Install Java'

- script: |
    echo "Downloading Maven..."
    wget -q https://apache.osuosl.org/maven/maven-3/3.9.3/binaries/apache-maven-3.9.3-bin.tar.gz
    tar -xzf apache-maven-3.9.3-bin.tar.gz -C /tmp
    mv /tmp/apache-maven-3.9.3 /usr/share/maven

    echo "Configuring Maven environment variables..."
    export MAVEN_HOME=/usr/share/maven
    export PATH=$MAVEN_HOME/bin:$PATH
  displayName: 'Install Maven'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    mavenAuthenticateFeed: false
    goals: 'clean package'
  displayName: 'Maven Build'

- task: CopyFiles@2
  inputs:
    contents: '**/*.war'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy WAR artifact'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'war'
  displayName: 'Publish Artifact'