# azure-pipelines.yml

trigger:
  branches:
    include:
      - main

pool: default

steps:
- script: |
    echo "Installing Java JDK..."
    sudo apt-get update
    sudo apt-get install -y openjdk-8-jdk

    echo "Configuring Java environment variables..."
    export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
    export PATH=$JAVA_HOME/bin:$PATH
  displayName: 'Install Java'
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '8'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- script: |
    echo "Downloading Maven..."
    wget -q https://apache.osuosl.org/maven/maven-3/3.9.3/binaries/apache-maven-3.9.3-bin.tar.gz
    tar -xzf apache-maven-3.9.3-bin.tar.gz -C /tmp
    sudo mv /tmp/apache-maven-3.9.3 /usr/share/maven

    echo "Configuring Maven environment variables..."
    export MAVEN_HOME=/usr/share/maven
    export PATH=$MAVEN_HOME/bin:$PATH
  displayName: 'Install Maven'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    mavenAuthenticateFeed: false
    goals: 'clean package'
  displayName: 'Maven Build'

- task: CopyFiles@2
  inputs:
    contents: '**/*.war'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy WAR artifact'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'war'
  displayName: 'Publish Artifact'