# azure-pipelines.yml

trigger:
  branches:
    include:
      - main

pool : default

steps:
- script: |
    echo "Installing Java JDK..."
    apt-get update
    apt-get install -y openjdk-8-jdk

    echo "Downloading Maven..."
    wget -q https://apache.osuosl.org/maven/maven-3/3.8.3/binaries/apache-maven-3.8.3-bin.tar.gz
    tar -xzf apache-maven-3.8.3-bin.tar.gz -C /usr/share/
    mv /usr/share/apache-maven-3.8.3 /usr/share/maven

    echo "Configuring Maven environment variables..."
    export MAVEN_HOME=/usr/share/maven
    export PATH=$MAVEN_HOME/bin:$PATH
  displayName: 'Install Java and Maven'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    goals: 'clean package'
  displayName: 'Maven Build'

- task: CopyFiles@2
  inputs:
    contents: '**/*.war'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy WAR artifact'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'war'
  displayName: 'Publish Artifact'
