# azure-pipelines.yml

trigger:
  branches:
    include:
      - main

pool: default

steps:
- script: |
    echo "Configuring Java environment variables..."
    export JAVA_HOME=$JAVA_HOME_8_X64
    export PATH=$JAVA_HOME/bin:$PATH
  displayName: 'Configure Java Home'

- script: |
    echo "Downloading Maven..."
    wget -q https://dlcdn.apache.org/maven/maven-3/3.9.3/binaries/apache-maven-3.9.3-bin.tar.gz
    tar -xzf apache-maven-3.9.3-bin.tar.gz -C /tmp
    sudo mv /tmp/apache-maven-3.9.3 /usr/share/maven

    echo "Configuring Maven environment variables..."
    export MAVEN_HOME=/usr/share/maven
    export PATH=$MAVEN_HOME/bin:$PATH
  displayName: 'Install Maven'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    goals: 'clean package'
  displayName: 'Maven Build'

- task: CopyFiles@2
  inputs:
    contents: '**/*.war'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy WAR artifact'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'war'
  displayName: 'Publish Artifact'
